### ISSUE TITLE
Hibernate support

### ISSUE THREAD

**Issue by Amitesh** [leinardi/ulauncher-exit-gnome#3]
Hi @leinardi ,

Thank you for creating usefull plugin.
Do you have any plan to add Hibernate option to the current list?

[feature-request]

Thanks,
Amitesh

**Comment by leinardi** [comment]
Hi @Amitesh, I would love to add the Hibernate option but `gnome-session-quit` does not provide this feature:
```
gnome-session-quit --help (return code: 0)
Usage:
  gnome-session-quit [OPTION...] 

Help Options:
  -h, --help       Show help options

Application Options:
  --logout         Log out
  --power-off      Power off
  --reboot         Reboot
  --force          Ignoring any existing inhibitors
  --no-prompt      Don't prompt for user confirmation
```

With ulauncher-exit-gnome I want to use only the options provided by `gnome-session-quit`.
But, if you are ok in trading logout with hibernate, you can use my other plugin: https://ext.ulauncher.io/-/github-leinardi-ulauncher-systemctl

![image](https://user-images.githubusercontent.com/273338/73605763-aeece280-45a2-11ea-8a47-387d3082b375.png)

This one uses `systemctl` for its actions and hibernate is one of the options (Gnome logout unfortunately isn't).

**Comment by Amitesh** [comment]
Thanks @leinardi  for sharing your system management extension link. it works like a charm.

Thank you!

**Comment by leinardi** [comment]
@Amitesh you are welcome :) And, if you like my plugins, consider starring them on GitHub, it will help making them more visible on the [Plugin repository website](https://ext.ulauncher.io/?sorting=github_stars).

- https://github.com/leinardi/ulauncher-exit-gnome
- https://github.com/leinardi/ulauncher-systemctl

**Comment by Amitesh** [comment]
Here you go!
It's done!!
